name:  Basic Workflow

on: 
  push:
    branches:  ["main"]

jobs:
  hello-world:
    runs-on:  ubuntu-latest


    steps:
      - name:  checkout repository
        uses:  actions/checkout@v3

      - name:  Say Hello
        run:  echo "Hello, GitHub Actions!"
    
